# Generated by Django 2.1.7 on 2019-06-28 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
