# Generated by Django 2.1.7 on 2019-06-28 23:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20190629_0155'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='time_added',
            field=models.TimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
